remote_theme: pages-themes/slate@v0.2.0
title: Takaaki Aoki's web page
description: Takaaki Aoki's web page
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have onetheme: jekyll-theme-minimal
  - jekyll-sitemap
