remote_theme: pages-themes/slate@v0.2.0
title: Takaaki Aoki's web page
description: Mathematical and geographical modelling・Network science・Nonlinear dynamics
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have onetheme: jekyll-theme-minimal
  - jekyll-sitemap
markdown: kramdown
