remote_theme: pages-themes/minimal@v0.2.0
title: Takaaki Aoki's web page
description: Mathematical and geographical modelling・Network science・Nonlinear dynamics
markdown: kramdown
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have onetheme: jekyll-theme-minimal
  - jekyll-sitemap
author:
  name: Takaaki Aoki
  email: "takaaki.aoki.work@gmail.com"
google_analytics: [G-BXEGP1YWQD]